name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Debug step to ensure frontend folder structure
      - name: List files in frontend directory
        run: |
          ls -la frontend

      # Cache frontend dependencies
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      # Install frontend dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      # Verify Node version
      - name: Verify Node version
        run: node -v

      # Build React App
      - name: Build React App
        run: npm run build
        working-directory: frontend

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          curl -X POST ${{ secrets.FRONTEND_DEPLOY_HOOK }}
